---
name: Publish

on:
  push:
    branches:
      - main
    paths:
      - '**.Dockerfile'
  workflow_dispatch:

jobs:
  paths-filter:
    name: Determine changed file(s)
    if: ${{ (github.event_name != 'schedule') && (github.event_name != 'workflow_dispatch') }}
    runs-on: ubuntu-latest
    outputs:
      alma-9: ${{ steps.changes.outputs.alma-9 }}
      alma-8: ${{ steps.changes.outputs.alma-8 }}
      debian-11: ${{ steps.changes.outputs.debian-11 }}
      ubuntu-2204: ${{ steps.changes.outputs.ubuntu-2204 }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            alma-9:
              - 'alma_9.Dockerfile'
            alma-8:
              - 'alma_9.Dockerfile'
            debian-11:
              - 'debian_11.Dockerfile'
            ubuntu-2204:
              - 'ubuntu_2204.Dockerfile'

  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dfuchs/alma-9-ansible

      - name: Login to Docker Hub repository
        uses: docker/login-action@v3
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push (alma-9)
        uses: docker/build-push-action@v6
        if: ${{ (steps.changes.outputs.alma-9 == 'true') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
        with:
          context: .
          file: alma_9.Dockerfile
          push: true
          tags: dfuchs/alma-9-ansible:latest

      - name: Build and push (alma-8)
        uses: docker/build-push-action@v6
        if: ${{ (steps.changes.outputs.alma-8 == 'true') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
        with:
          context: .
          file: alma_8.Dockerfile
          push: true
          tags: dfuchs/alma-8-ansible:latest

      - name: Build and push (debian-11)
        uses: docker/build-push-action@v6
        if: ${{ (steps.changes.outputs.debian-11 == 'true') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
        with:
          context: .
          file: debian_11.Dockerfile
          push: true
          tags: dfuchs/debian-11-ansible:latest

      - name: Build and push (ubuntu-22.04)
        uses: docker/build-push-action@v6
        if: ${{ (steps.changes.outputs.ubuntu-2204 == 'true') || (github.event_name == 'schedule') || (github.event_name == 'workflow_dispatch') }}
        with:
          context: .
          file: ubuntu_2204.Dockerfile
          push: true
          tags: dfuchs/ubuntu-22.04-ansible:latest
