---
name: Publish

on:
  push:
    branches:
      - main
    paths:
      - '**.Dockerfile'
      - 'README.md'
  workflow_dispatch:
    inputs:
      build:
        description: 'Build and push image to Docker Hub'
        required: false
        default: 'none'
        type: choice
        options:
          - all
          - alma-9
          - alma-8
          - debian-12
          - debian-11
          - ubuntu-24.04
          - ubuntu-22.04
          - none
      image:
        description: 'Docker Hub repo description update'
        required: false
        default: 'none'
        type: choice
        options:
          - all
          - alma-9
          - alma-8
          - debian-12
          - debian-11
          - ubuntu-24.04
          - ubuntu-22.04
          - none

jobs:
  detect-changes:
    name: Detect changed files
    runs-on: ubuntu-latest
    outputs:
      alma_9: ${{ steps.changes.outputs.alma_9_any_changed }}
      alma_8: ${{ steps.changes.outputs.alma_8_any_changed }}
      debian_12: ${{ steps.changes.outputs.debian_12_any_changed }}
      debian_11: ${{ steps.changes.outputs.debian_11_any_changed }}
      ubuntu_2404: ${{ steps.changes.outputs.ubuntu_2404_any_changed }}
      ubuntu_2204: ${{ steps.changes.outputs.ubuntu_2204_any_changed }}
      readme: ${{ steps.changes.outputs.readme_any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v46
        with:
          files_yaml: |
            alma_9:
              - alma_9.Dockerfile
            alma_8:
              - alma_8.Dockerfile
            debian_12:
              - debian_12.Dockerfile
            debian_11:
              - debian_11.Dockerfile
            ubuntu_2404:
              - ubuntu_2404.Dockerfile
            ubuntu_2204:
              - ubuntu_2204.Dockerfile
            readme:
              - README.md

  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    needs: detect-changes
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-9')) || (github.event_name == 'push' && needs.detect-changes.outputs.alma_9 == 'true') && 'dfuchs/alma-9-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-8')) || (github.event_name == 'push' && needs.detect-changes.outputs.alma_8 == 'true') && 'dfuchs/alma-8-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'debian-12')) || (github.event_name == 'push' && needs.detect-changes.outputs.debian_12 == 'true') && 'dfuchs/debian-12-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'debian-11')) || (github.event_name == 'push' && needs.detect-changes.outputs.debian_11 == 'true') && 'dfuchs/debian-11-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'ubuntu-24.04')) || (github.event_name == 'push' && needs.detect-changes.outputs.ubuntu_2404 == 'true') && 'dfuchs/ubuntu-24.04-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'ubuntu-22.04')) || (github.event_name == 'push' && needs.detect-changes.outputs.ubuntu_2204 == 'true') && 'dfuchs/ubuntu-22.04-ansible' || '' }}

      - name: Login to Docker Hub repository
        uses: docker/login-action@v3
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push (alma-9)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-9')) || (github.event_name == 'push' && needs.detect-changes.outputs.alma_9 == 'true') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: alma_9.Dockerfile
          push: true
          tags: dfuchs/alma-9-ansible:latest

      - name: Build and push (alma-8)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-8')) || (github.event_name == 'push' && needs.detect-changes.outputs.alma_8 == 'true') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: alma_8.Dockerfile
          push: true
          tags: dfuchs/alma-8-ansible:latest

      - name: Build and push (debian-12)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'debian-12')) || (github.event_name == 'push' && needs.detect-changes.outputs.debian_12 == 'true') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: debian_12.Dockerfile
          push: true
          tags: dfuchs/debian-12-ansible:latest

      - name: Build and push (debian-11)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'debian-11')) || (github.event_name == 'push' && needs.detect-changes.outputs.debian_11 == 'true') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: debian_11.Dockerfile
          push: true
          tags: dfuchs/debian-11-ansible:latest

      - name: Build and push (ubuntu-24.04)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'ubuntu-24.04')) || (github.event_name == 'push' && needs.detect-changes.outputs.ubuntu_2404 == 'true') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ubuntu_2404.Dockerfile
          push: true
          tags: dfuchs/ubuntu-24.04-ansible:latest

      - name: Build and push (ubuntu-22.04)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'ubuntu-22.04')) || (github.event_name == 'push' && needs.detect-changes.outputs.ubuntu_2204 == 'true') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ubuntu_2204.Dockerfile
          push: true
          tags: dfuchs/ubuntu-22.04-ansible:latest

  update-dockerhub-description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    needs: detect-changes
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
    steps:
      - uses: actions/checkout@v4

      - name: Update Docker Hub description (alma-9)
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.image == 'all' || github.event.inputs.image == 'alma-9') || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/alma-9-ansible

      - name: Update Docker Hub description (alma-8)
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.image == 'all' || github.event.inputs.image == 'alma-8') || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/alma-8-ansible

      - name: Update Docker Hub description (debian-12)
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.image == 'all' || github.event.inputs.image == 'debian-12') || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/debian-12-ansible

      - name: Update Docker Hub description (debian-11)
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.image == 'all' || github.event.inputs.image == 'debian-11') || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/debian-11-ansible

      - name: Update Docker Hub description (ubuntu-24.04)
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.image == 'all' || github.event.inputs.image == 'ubuntu-24.04') || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/ubuntu-24.04-ansible

      - name: Update Docker Hub description (ubuntu-22.04)
        if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.image == 'all' || github.event.inputs.image == 'ubuntu-22.04') || (github.event_name == 'push' && needs.detect-changes.outputs.readme == 'true') }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/ubuntu-22.04-ansible
