---
name: Publish

on:
  push:
    branches:
      - main
    paths:
      - '**.Dockerfile'
      - 'README.md'
  workflow_dispatch:
    inputs:
      build:
        description: 'Build and push image to Docker Hub'
        required: false
        default: 'none'
        type: choice
        options:
          - all
          - alma-9
          - alma-8
          - debian-11
          - ubuntu-22.04
          - none
      image:
        description: 'Docker Hub repo description update'
        required: false
        default: 'none'
        type: choice
        options:
          - all
          - alma-9
          - alma-8
          - debian-11
          - ubuntu-22.04
          - none

jobs:
  build-and-push:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-9')) || contains(github.event.head_commit.modified, 'alma_9.Dockerfile') && 'dfuchs/alma-9-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-8')) || contains(github.event.head_commit.modified, 'alma_8.Dockerfile') && 'dfuchs/alma-8-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'debian-11')) || contains(github.event.head_commit.modified, 'debian_11.Dockerfile') && 'dfuchs/debian-11-ansible' || '' }}
            ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'ubuntu-22.04')) || contains(github.event.head_commit.modified, 'ubuntu_2204.Dockerfile') && 'dfuchs/ubuntu-22.04-ansible' || '' }}

      - name: Login to Docker Hub repository
        uses: docker/login-action@v3
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push (alma-9)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-9')) || contains(github.event.head_commit.modified, 'alma_9.Dockerfile') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: alma_9.Dockerfile
          push: true
          tags: dfuchs/alma-9-ansible:latest

      - name: Build and push (alma-8)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'alma-8')) || contains(github.event.head_commit.modified, 'alma_8.Dockerfile') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: alma_8.Dockerfile
          push: true
          tags: dfuchs/alma-8-ansible:latest

      - name: Build and push (debian-11)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'debian-11')) || contains(github.event.head_commit.modified, 'debian_11.Dockerfile') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: debian_11.Dockerfile
          push: true
          tags: dfuchs/debian-11-ansible:latest

      - name: Build and push (ubuntu-22.04)
        if: ${{ (github.event_name == 'workflow_dispatch' && (github.event.inputs.build == 'all' || github.event.inputs.build == 'ubuntu-22.04')) || contains(github.event.head_commit.modified, 'ubuntu_2204.Dockerfile') }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ubuntu_2204.Dockerfile
          push: true
          tags: dfuchs/ubuntu-22.04-ansible:latest

  update-dockerhub-description:
    name: Update Docker Hub Description
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'push' && contains(github.event.head_commit.modified, 'README.md')) }}
    steps:
      - uses: actions/checkout@v4
      - name: Update Docker Hub description (alma-9)
        if: ${{ github.event_name == 'push' || github.event.inputs.image == 'all' || github.event.inputs.image == 'alma-9' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/alma-9-ansible
      - name: Update Docker Hub description (alma-8)
        if: ${{ github.event_name == 'push' || github.event.inputs.image == 'all' || github.event.inputs.image == 'alma-8' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/alma-8-ansible
      - name: Update Docker Hub description (debian-11)
        if: ${{ github.event_name == 'push' || github.event.inputs.image == 'all' || github.event.inputs.image == 'debian-11' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/debian-11-ansible
      - name: Update Docker Hub description (ubuntu-22.04)
        if: ${{ github.event_name == 'push' || github.event.inputs.image == 'all' || github.event.inputs.image == 'ubuntu-22.04' }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: dfuchs
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          repository: dfuchs/ubuntu-22.04-ansible
